# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#home"
  weight = 10

[[main]]
  name = "About"
  url = "#about"
  weight = 20

#[[main]]
#  name = "Invited speakers"
#  url = "speakers"
#  weight = 40

[[main]]
#  identifier = "dropcfp"
  name = "Call for Participation"
  url = "cfp"
  weight = 30

#[[main]]
#  name = "General CfP information"
#  url = "cfp"
#  parent = "dropcfp"
#  weight = -30

#[[main]]
#  name = "Research Track"
#  url = "cfpresearch"
#  parent = "dropcfp"
#  weight = 30

#[[main]]
#  name = "Policy & Practice Track"
#  url = "cfppolicyandpractice"
#  parent = "dropcfp"
#  weight = 40


#[[main]]
#  name = "Research Track (Español)"
#  url = "cfpresearchspanish"
#  parent = "dropcfp"
#  weight = 50


#[[main]]
#  name = "Policy & Practice Track (Español)"
#  url = "cfppolicyspanish"
#  parent = "dropcfp"
#  weight = 60


[[main]]
  name = "Registration"
  url = "registration"
  weight = 40

#[[main]]
#  name = "Program"
#  url = "program"
#  weight = 30

[[main]]
  name = "Program"
  url = "program"
  weight = 50

[[main]]
  identifier = "schedule"
  name = "Schedule"
  url = "schedule"
  weight = -30
  parent = "program"
  
[[main]]
  name = "Organizers"
  url = "committee"
  weight = 60

[[main]]
  name = "Invited Speakers"
  url = "speakers"
  weight = 70

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80

[[main]]
  name = "MD4SG"
  url = "https://md4sg.com"
  weight = 90

#[[main]]
#  name = "CFP Research Track"
#  url = "cfpresearch"
#  weight = 90

#[[main]]
#  name = "CFP Policy Track"
#  url = "cfppolicypractice"
#  weight = 100

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
